package jsonclass

case class Metadata(
   accession_no_csv: String,
   Image: String,
   object_work_type: String,
   title_text: String,
   preference: String,
   title_language: String,
   creator_2: String,
   creator_1: String,
   creator_role: String,
   creation_date: String,
   creation_place_original_location: String,
   styles_periods_indexing_terms: String,
   inscriptions: String,
   inscription_language: String,
   scale_type: String,
   shape: String,
   materials_name: String,
   techniques_name: String,
   object_colour: String,
   edition_description: String,
   physical_appearance: String,
   subject_terms_1: String,
   subject_terms_2: String,
   subject_terms_3: String,
   subject_terms_4: String,
   context_1: String,
   context_2: String,
   context_3: String,
   context_4: String,
   context_5: String,
   context_6: String,
   context_7: String,
   context_8: String,
   context_9: String,
   context_10: String,
   context_11: String,
   context_12: String,
   context_13: String,
   context_14: String,
   context_15: String,
   context_16: String,
   context_17: String,
   context_18: String,
   context_19: String,
   context_20: String,
   context_21: String,
   context_22: String,
   context_23: String,
   context_24: String,
   sgcool_label_text: String
) extends Serializable{
    override def toString = s"Metadata(accession_no_csv:$accession_no_csv, Image:$Image, object_work_type:$object_work_type, title_text:$title_text, preference:$preference, title_language:$title_language, creator_2:$creator_2, creator_1:$creator_1, creator_role:$creator_role, creation_date:$creation_date, creation_place_original_location:$creation_place_original_location, styles_periods_indexing_terms:$styles_periods_indexing_terms, inscriptions:$inscriptions, inscription_language:$inscription_language, scale_type:$scale_type, shape:$shape, materials_name:$materials_name, techniques_name:$techniques_name, object_colour:$object_colour, edition_description:$edition_description, physical_appearance:$physical_appearance, subject_terms_1:$subject_terms_1, subject_terms_2:$subject_terms_2, subject_terms_3:$subject_terms_3, subject_terms_4:$subject_terms_4, context_1:$context_1, context_2:$context_2, context_3:$context_3, context_4:$context_4, context_5:$context_5, context_6:$context_6, context_7:$context_7, context_8:$context_8, context_9:$context_9, context_10:$context_10, context_11:$context_11, context_12:$context_12, context_13:$context_13, context_14:$context_14, context_15:$context_15, context_16:$context_16, context_17:$context_17, context_18:$context_18, context_19:$context_19, context_20:$context_20, context_21:$context_21, context_22:$context_22, context_23:$context_23, context_24:$context_24, sgcool_label_text:$sgcool_label_text)"
}
